simple_voting-dev/api/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('survey/create/', create_survey),
    path('survey/get/', get_survey),
    path('survey/history/', get_user_history),
    path('survey/new/', get_new_surveys),
    path('survey/user/', get_user_surveys),
    path('survey/vote/', vote_survey),
]

simple_voting-dev/simple_votings/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('vote.urls')),
    path('api/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# https://docs.djangoproject.com/es/3.1/howto/static-files/#serving-files-uploaded-by-a-user-during-development

simple_voting-dev/vote/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index_page),
    path('account/signup/', signup),
    path('account/login/', login),
    path('account/logout/', logout),
    path('account/', view_account),
    path("history/", view_history),
    path('issue/create/', create_issue),
    path('issue/chats/', issue_chats),
    path('issue/close/', close_issue),
    path("issue/messages/", issue_chat_messages),
    path("admin/", admin_issues),
]

simple_voting-dev/vote/models.py
import os
import uuid

from django.db import models
from django.conf import settings
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.contrib.auth.hashers import make_password, check_password



def get_media_root():
    path = os.path.join(settings.MEDIA_ROOT)

    # Ensure path to file is valid
    try:
        os.makedirs(path)
    finally:
        return path

def save_file(file_data):
    filename = uuid.uuid4().hex
    media_path = get_media_root()
    filepath = os.path.join(media_path, filename)
    with open(filepath, 'wb') as f:
        for chunk in file_data.chunks():
            f.write(chunk)
    return filename

class User(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(max_length=254, unique=True)
    password = models.CharField(max_length=100)
    profile_picture_file = models.CharField(max_length=32, null=True, default=None)
    username = models.CharField(max_length=50, default="Anonymous")
    is_superuser = models.BooleanField(default=False)

    @classmethod
    def create(cls, **obj_fields):
        plain_passwd = obj_fields.get('password')
        obj_fields['password'] = make_password(plain_passwd)

        username = obj_fields.get('username')
        if username == '':
            obj_fields['username'] = 'Anonymous'

        return cls(**obj_fields)

    def check_password(self, password: str):
        return check_password(password, self.password)

    @staticmethod
    def check_credentials(email: str, password: str):
        try:
            user = User.objects.get(email=email)
            if user.check_password(password):
                return user
        except User.DoesNotExist:
            pass

        return None

    @staticmethod
    def update_user(user, email, password, username, reset_username,
                    profile_picture, reset_profile_picture, **gibberish):
        if email:
            if User.objects.filter(email=email) and user.email != email:
                return 'Provided email address is already taken'
            else:
                user.email = email
        
        if password:
            user.password = make_password(password)

        if reset_username:
            user.username = 'Anonymous'
        elif username:
            user.username = username

        # If profile picture is being changed
        if reset_profile_picture or profile_picture:
            # Delete previous profile picture
            media_path = get_media_root()
            if user.profile_picture_file is not None:
                filepath = os.path.join(media_path, user.profile_picture_file)

                try:
                    os.remove(filepath)
                except FileNotFoundError:
                    pass
                
                user.profile_picture_file = None

            # If file is being uploaded, create new with random filename
            if profile_picture:
                user.profile_picture_file = save_file(profile_picture)

        user.save()
        return None

    def get_voted_surveys(self):
        vote_option_ids = Vote.objects.filter(user=self).values_list('vote_option')
        vote_options = VoteOption.objects.filter(id__in=vote_option_ids)
        survey_ids = vote_options.values_list('survey').distinct()
        return Survey.objects.filter(id__in=survey_ids)

    def best_survey(self):
        user_surveys = Survey.objects.filter(user=self)
        if user_surveys.count() == 0:
            return None
            
        best_survey = user_surveys[0]
        for survey in user_surveys[1:]:
            if survey.votes.count() > best_survey.votes.count():
                best_survey = survey

        return best_survey

    def get_unvoted_surveys(self):
        user_votes = Vote.objects.filter(user=self).values('vote_option_id')
        surveys_voted = VoteOption.objects.filter(id__in=user_votes).values('survey_id').distinct()
        return Survey.objects.exclude(id__in=surveys_voted)

    def add_account_context(self, context):
        context['number_of_surveys'] = Survey.objects.filter(user=self).count()
        context['best_survey'] = None

        best_survey = self.best_survey()
        if best_survey is not None:
            context['best_survey'] = best_survey.get_render_info(context['user'])

        return context


class Survey(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(default="")
    allow_multiple = models.BooleanField(default=False)
    creation_datetime = models.DateTimeField(default=timezone.now)
    
    @property
    def vote_options(self):
        return VoteOption.objects.filter(survey=self)

    @property
    def votes(self):
        return Vote.objects.filter(vote_option__in=self.vote_options)

    @classmethod
    def create(cls, user, title, description, allow_multiple, vote_options, **fields):
        survey = Survey(
            user = user,
            title = title,
            description = description,
            allow_multiple = True if allow_multiple else False  # For some reason, Django forms
                                                                # return allow_multiple as None
                                                                # or as 'on', so this workaround
                                                                # is required :\
        )
        survey.save()

        for option in vote_options:
            vote_option = VoteOption(
                survey = survey,
                content = option
            )
            vote_option.save()

        return survey

    def get_voted_fraction(self, vote_option):
        unique_users_votes = self.votes.values('user').distinct().count()
        if unique_users_votes == 0:
            return 0

        option_votes = vote_option.votes.count()
        return option_votes / unique_users_votes
    
    def get_render_info(self, user):
        render_info = {
            'allow_multiple': self.allow_multiple,
            'creation_datetime': self.creation_datetime,
            'title': self.title,
            'description': self.description,
            'vote_options': {},
            'user': {
                'id': self.user.id,
                'profile_picture': self.user.profile_picture_file,
                'username': self.user.username,
            },
            'show_results': self in user.get_voted_surveys(),
        }

        for vote_option in self.vote_options:
            render_info['vote_options'] |= {
                str(vote_option.id): {
                    'content': vote_option.content,
                    'voted_fraction': self.get_voted_fraction(vote_option)
                }
            }

        return render_info

    @staticmethod
    def get_survey_slice(surveys, start_from, amount):
        surveys = surveys.order_by('-creation_datetime')
        try:
            amount = int(amount)
        except (ValueError, TypeError):
            amount = 1

        try:
            start_index = 0
            start_uuid = uuid.UUID(start_from)
            for idx, survey in enumerate(surveys):
                if survey.id == start_uuid:
                    start_index = idx + 1
                    break
        except (ValueError, TypeError, ValidationError):
            pass
        
        survey_slice = list(surveys[start_index:start_index + amount])
        any_left = start_index + amount < len(surveys)
        if len(survey_slice) != 0: 
            last_id = survey_slice[-1].id
        elif len(surveys) != 0:
            last_id = surveys.last().id
        else:
            last_id = None

        return survey_slice, any_left, last_id

        

class VoteOption(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

    @property
    def votes(self):
        return Vote.objects.filter(vote_option=self)


class Vote(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    vote_option = models.ForeignKey(VoteOption, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    vote_datetime = models.DateTimeField(default=timezone.now)


class Issue(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    is_closed = models.BooleanField(default=False)
    creation_datetime = models.DateTimeField(default=timezone.now)


class IssueMessage(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE)
    content = models.TextField()
    trouble_file = models.CharField(max_length=32, null=True, default=None)
    from_support = models.BooleanField(default=False)
    send_datetime = models.DateTimeField(default=timezone.now)

simple_voting-dev/vote/forms.py
from django import forms

class UserSignupForm(forms.Form):
    email = forms.EmailField(label="Email", max_length=254, required=True)
    password = forms.CharField(label="Password", min_length=8, max_length=128, 
                               widget=forms.PasswordInput(), required=True)
    confirm_password = forms.CharField(label="Confirm password", min_length=8, max_length=128,
                                       widget=forms.PasswordInput(), required=True)
    username = forms.CharField(label="Username", max_length=50, required=False)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError('passwords do not match')


class UserLoginForm(forms.Form):
    email = forms.EmailField(label="Email", max_length=254, required=True)
    password = forms.CharField(label="Password", min_length=8, max_length=128, 
                               widget=forms.PasswordInput(), required=True)


class UserEditForm(forms.Form):
    email = forms.EmailField(label="New email", max_length=254, required=False)
    password = forms.CharField(label="New password", min_length=8, max_length=128, 
                               widget=forms.PasswordInput(), required=False)
    confirm_password = forms.CharField(label="Confirm new password", min_length=8, max_length=128,
                                       widget=forms.PasswordInput(), required=False)
    username = forms.CharField(label="New username", max_length=50, required=False)
    reset_username = forms.BooleanField(label="Reset to default", required=False)
    profile_picture = forms.FileField(label='Upload profile picture', required=False)
    reset_profile_picture = forms.BooleanField(label="Reset to default", required=False)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password is not None and password != confirm_password:
            raise forms.ValidationError('passwords do not match')
        return cleaned_data

class UserIssuesForm(forms.Form):
    title = forms.CharField(label= "Title", min_length=10, max_length=100,required=True)
    content = forms.CharField(label="Description of issue", required=True)
    trouble_file = forms.FileField(label='Upload Files to Help Issue', required=False)
    def clean(self):
        cleaned_data = super().clean()
        
        if cleaned_data.get('title') is None or cleaned_data.get('content') is None:
            raise forms.ValidationError("Title or Description of issue can't be empty")

        return cleaned_data
class UserIssuesMsgForm(forms.Form):
    content = forms.CharField(label= "Create Message", required=True)
    trouble_file = forms.FileField(label='Upload Files', required=False)
    def clean(self):
        cleaned_data = super().clean()
        
        if cleaned_data.get('content') is None:
            raise forms.ValidationError("Content of Message goes BRRRRRR")
        return cleaned_data

class SurveyCreateForm(forms.Form):
    title = forms.CharField(label="Title", max_length=200, required=True)
    description = forms.CharField(label="Description", required=False)
    type = forms.ChoiceField(choices=[(1, "1:N"),
                                      (2, "M:N"), 
                                      (3, "YES/NO")], label="Type", required=False)
    allow_multiple = forms.BooleanField(required=False)

    def clean(self):
        cleaned_data = super().clean()

        options = [x.strip() 
                   for x in self.data.getlist('vote_option') 
                   if x.strip() != ""]

        if options is None or len(options) < 1:
            raise forms.ValidationError(
                'Surveys must have at least 1 vote option'
            )

        if any(len(option) > 100 for option in options):
            raise forms.ValidationError(
                'Vote options can\'t be longer than 100 characters'
            )

        cleaned_data['vote_option'] = options
        return cleaned_data


def nullable_pop(dict_, key):
    try:
        return dict_.pop(key)
    except KeyError:
        return None

class SurveyVoteForm(forms.Form):
    def __init__(self, *args, **kwargs):
        fields = nullable_pop(kwargs, 'vote_options')

        super().__init__(*args, **kwargs)

        if fields:
            self.fields['options'] = forms.MultipleChoiceField(
                                        widget=forms.CheckboxSelectMultiple, 
                                        choices=fields, 
                                        required=True)

    def clean(self):
        cleaned_data = super().clean()
        
        cleaned_data['choice_ids'] = self.data.getlist('choice_id') + \
                                    self.data.getlist('choice_id[]')    # :\
                                    
        if len(cleaned_data['choice_ids']) == 0:
            raise forms.ValidationError(
                'You. Must. Vote.'
            )

        return cleaned_data

simple_voting-dev/vote/templates/account.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    {% if user == owner %}
        Your account
    {% else %}
        {{owner.username}}'s account
    {% endif %}
{% endblock %}

{% block content %}
{% if user == owner %}
    <header class="title">Your account</header>
{% else %}
    <header class="title">{{owner.username}}'s account</header>
{% endif %}

<div class="profile">
    <div class="info">
        {% if owner.profile_picture_file %}
            <img src="{% get_media_prefix %}{{owner.profile_picture_file}}" alt="Avatar" class="avatar">
        {% else %}
            <img src="{% static 'img/default_profile_picture.png' %}" alt="Avatar" class="avatar">
        {% endif %}

        <p><b>Username: </b>{{owner.username}}</p>

        {% if user == owner %}
            <p><b>Email:</b> {{owner.email}}</p>
        {% endif %}

        <p><b>Surveys created:</b> {{number_of_surveys}}</p>

        {% if owner.is_superuser %}
        <p><b>[ Administrator ]</b></p>
        {% endif %}

        {% if user == owner %}
            <a href="#popup">Edit profile</a>
        {% endif %}
    </div>

    {% if best_survey %}
    <div class="most-popular-container">
        <h3>Most popular survey:</h3>
        <div class="most-popular-survey-container">
            {% with survey=best_survey %}
                {% include 'survey_base.html' %}
            {% endwith %}
        </div>
    </div>
    {% endif %}
</div>

{% if user == owner %}
    <header class="title">Your surveys</header>
{% else %}
    <header class="title">{{owner.username}}'s surveys</header>
{% endif %}
<div id="user-surveys">
    <div id="survey-container" class="surveys"></div>

    <form id="load-more">
        {% csrf_token %}
        <input type="hidden" name="ajax-url" value="/api/survey/user/">
        <input type="hidden" name="user_id" value="{{owner.id}}">
        <button type="submit">Load more</button>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/surveys.js' %}"></script>
<script src="{% static 'js/popup.js' %}"></script>
<script>
    // Show filename when file is uploaded
    function getName(str) {
        let idx;
        if (str.lastIndexOf('\\')) idx = str.lastIndexOf('\\') + 1;
        else idx = str.lastIndexOf('/') + 1;

        let filename = str.slice(idx);
        let uploaded = document.getElementById("fileformlabel");
        uploaded.innerHTML = filename;
    }
</script>
{% if form_errors %}
<script>
    $(document).ready(function(){
        window.location = '#popup'
    });
</script>
{% endif %}  
{% endblock %}


{% block popup %}
{% include 'survey_popup.html' %}
<div id="popup" class="overlay">
    <div class="popup">
        <header>
            <span>Edit account</span>
            <a class="close" href="#">&times;</a>
        </header>
        <div class="content">
            <form action="/account/" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="checkbox" name="allow_multiple" id="id_allow_multiple" hidden>

                <div class="field">
                    <span class="label">Username:</span>
                    <input type="text" name="username" maxlength="50" id="id_username">
                </div>

                <div class="field">
                    <span class="label">Email:</span>
                    <input type="email" name="email" maxlength="254" id="id_email">
                </div>

                <div class="field">
                    <span class="label">New password:</span>
                    <input type="password" name="password" minlength="8" maxlength="128" id="id_password">
                </div>

                <div class="field">
                    <span class="label">Confirm new password:</span>
                    <input type="password" name="confirm_password" minlength="8" maxlength="128" id="id_confirm_password">
                </div>
                
                <div class="field">
                    <span class="label">Upload profile picture:</span>
                    <div class="fileform">
                        <div id="fileformlabel"></div>
                        <div class="selectbutton">Browse</div>
                        <input type="file" name="profile_picture" id="id_profile_picture" onchange="getName(this.value);"/>
                    </div>
                </div>
                
                {% if form_errors %} 
                <div class="field">
                    <div class="error">
                        {% for error in form_errors %}
                            <div>{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>
                {% endif %} 
                
                <div class="send-button-container">
                    <button type="submit" class="send_button">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

simple_voting-dev/vote/templates/base.html
{% load static %}
{% load tz %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block page_title %}{% endblock %}</title>
        
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        {% block scripts %}{% endblock %}
    </head>
    <body>
        {% include 'menu.html' %}
        {% block content %}{% endblock %}
        {% block popup %}{% endblock %}
    </body>
</html>

simple_voting-dev/vote/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{status_code}}</title>
</head>
<body>
    <h1>{{error}}</h1>
    <hr>
    <h3>{{details}}</h3>
    <a href="javascript:history.back()">Go back</a>
</body>
</html>

simple_voting-dev/vote/templates/index.html
{% extends "base.html" %}
{% load tz %}
{% load static %}

{% block page_title %}
Home page - Simple Votings
{% endblock %}


{% block content %} 
<div class="block">
    <a class="standart_button" href="#popup">Create new survey</a>
</div>

<header class="title">Vote right now</header>
<div id="user-surveys">
    <div id="survey-container" class="surveys"></div>

    <form id="load-more">
        {% csrf_token %}
        <input type="hidden" name="ajax-url" value="/api/survey/new/">
        <button type="submit">Load more</button>    
   </form>
</div>
{% endblock %}

{% block popup %}
{% if user %}
{% include 'survey_popup.html' %}

<div id="popup" class="overlay">
    <div class="popup">
        <header>
            <span>Create survey</span>
            <a class="close" href="#">&times;</a>
        </header>
        <div class="content">
            <form action="/api/survey/create/" method="post">
                {% csrf_token %}
                <input type="checkbox" name="allow_multiple" id="id_allow_multiple" hidden>

                <span>Creation date: {{ current_time | date:"d.m.Y" }}</span>

                <div class="field"> 
                    <span>Type:</span>
                    <button type="button" title="People can choose only one option" class="type type-1">1:N</button> 
                    <button type="button" title="People can choose one or more options" class="type type-2">M:N</button> 
                    <button type="button" title='People can only vote "yes" or "no"' class="type type-3">YES/NO</button>
                </div>
                
                <div class="field">
                    <span class="label">Title:</span>
                    <input type="text" name="title" maxlength="200" required id="id_title">
                </div>
                
                <div class="field">
                    <span class="label">Description:</span>
                    <textarea name="description" id="id_description" wrap="soft" cols="40" rows="3" class="description"></textarea>
                </div>
                
                <div class="field vote-options">
                    <span class="label">Vote options</span>
                    
                    <div class="vote-option remove-option-container">
                        <button type="button" class="icon remove-option"></button>
                        <input name="vote_option" type="text" maxlength="100" autocomplete="off">
                    </div>

                    <div class="vote-option remove-option-container">
                        <button type="button" class="icon remove-option"></button>
                        <input name="vote_option" type="text" maxlength="100" autocomplete="off">
                    </div>

                    <div class="vote-option add-option-container">
                        <button type="button" class="icon add-option"></button>
                        <input type="text">
                    </div>
                </div>
                
                <div class="send-button-container">
                    <button type="submit" class="send_button">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

{% block scripts %}
<script src="{% static 'js/popup.js' %}"></script>
<script src="{% static 'js/surveys.js' %}"></script>
<script src="{% static 'js/create_survey.js' %}"></script>
{% endblock %}

simple_voting-dev/vote/templates/issue_chat_messages.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% if user.is_superuser %}
<header class="title">Chat with {{current_issue.user.username}}</header>
{% else %}
<header class="title">Support</header>
{% endif %} 

<div class="block">
    <div class="issue-header">
        <header>{{current_issue.title}}</header>
        
        {% if not current_issue.is_closed and not user.is_superuser %}
        <form action="/issue/close/" method="post">
            {% csrf_token %}
            <input type="hidden" name="issue_id" value="{{current_issue.id}}">
            <button type="submit">Close issue</button>
        </form>
        {% endif %}
    </div>

    <div class="msg-container">
        {% for issue_msg in issue_msg_arr %}
            <div class="msg">
                {% if issue_msg.from_support %}
                    {% if issue_msg.content %}
                        <div class="support">{{issue_msg.content}}</div>
                    {% endif %}
                    {% if issue_msg.trouble_file %}
                        <img class="support" src="{% get_media_prefix %}{{ issue_msg.trouble_file }}">
                    {% endif %}
                {% else %}
                    {% if issue_msg.content %}
                        <div class="user">{{issue_msg.content}}</div>
                    {% endif %}
                    {% if issue_msg.trouble_file %}
                        <img class="user" src="{% get_media_prefix %}{{ issue_msg.trouble_file }}">
                    {% endif %}
                {% endif %}
            </div>
        {% endfor %}
    </div>
    {% if not current_issue.is_closed %}
    <form action="/issue/messages/" method="post" enctype="multipart/form-data" class="user-input">
        {% csrf_token %}
        <input type="hidden" name="issue_id" value="{{current_issue.id}}">

        <div class="fileform">
            <div id="fileformlabel"></div>
            <div class="selectbutton">Browse</div>
            <input type="file" name="trouble_file" id="id_trouble_file" onchange="getName(this.value);"/>
        </div>
        <div class="flex-container">
            <textarea type="text" name="content" autocomplete="off" required rows="1" id="id_content" class="user-msg"></textarea>
            <button class="send-msg-btn">send</button>
        </div>
    </div>
    {% else %}
    <div class="closed-help-container">
        <div class="closed-help">This issue was closed. Now it's read-only.</div>
    </div>
    {% endif %}
</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(() => {
        $(".msg-container").scrollTop($(".msg-container")[0].scrollHeight);
    });
    function getName(str) {
        let idx;
        if (str.lastIndexOf('\\')) idx = str.lastIndexOf('\\') + 1;
        else idx = str.lastIndexOf('/') + 1;

        let filename = str.slice(idx);
        let uploaded = document.getElementById("fileformlabel");
        uploaded.innerHTML = filename;
    }
</script>
{% endblock %}

simple_voting-dev/vote/templates/issue_chats.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
Issue Chats - Simple Votings
{% endblock %}

{% block content %} 
{% if not user.is_superuser %}
<div class="block">
    <a href="#popup" class="standart_button">Create an issue</a>
</div>
{% endif %}

<header class="title">User issues</header>

<div class="issue-container">
    <div class="container color-white">
        <div class="issue">
            {%for issue_title in issues_arr%}
                <a href="/issue/messages?id={{issue_title.id}}">
                    <p>{{issue_title.title}}</p>
                    
                    {% if issue_title.is_closed %}
                        <b>[closed]</b>
                    {% endif %}
                </a>
            {%endfor%}
        </div>
    </div>
</div>
{% endblock %}


{% block popup %}
{% if user %}
    <div id="popup" class="overlay">
        <div class="popup">
            <div class="header_for_pop_up">
                <header>Create issue</header>
                <a class="close" href="#">&times;</a>
            </div>
            <div class="content">
                <form action="/issue/create/" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="field">
                        <span class="label">Title:</span>
                        <input type="text" name="title" maxlength="100" minlength="10" required id="id_title">
                    </div>
                    
                    <div class="field">
                        <span class="label">Description:</span>
                        <textarea name="content" id="id_content" wrap="soft" cols="40" rows="3"></textarea>
                    </div>
                    
                    <div class="field">
                        <span class="label">Upload screenshot:</span>
                        <div class="fileform">
                            <div id="fileformlabel"></div>
                            <div class="selectbutton">Browse</div>
                            <input type="file" name="trouble_file" id="id_trouble_file" onchange="getName(this.value);"/>
                        </div>
                    </div>

                    {% if form_errors %} 
                    <div class="field">
                        <div class="error">
                            {% for error in form_errors %}
                                <div>{{ error }}</div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endif %} 
                    
                    <div class="send-button-container">
                        <button type="submit" class="send_button">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}

{% block scripts %}
<script src="{% static 'js/popup.js' %}"></script>
<script>
    // Show filename when file is uploaded
    function getName(str) {
        let idx;
        if (str.lastIndexOf('\\')) idx = str.lastIndexOf('\\') + 1;
        else idx = str.lastIndexOf('/') + 1;

        let filename = str.slice(idx);
        let uploaded = document.getElementById("fileformlabel");
        uploaded.innerHTML = filename;
    }
</script>
{% endblock %}